example.property: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://lpgen2-postgres.cyhkmsyvljss.us-east-2.rds.amazonaws.com:5432/cocktails" 
spring.datasource.username: "postgres"
spring.datasource.password: "postgresql"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
cocktail_url: "https://app.liquidpresentation.com"