server:
  port: 9011
    
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://34.194.60.121:8901/auth/user        

amazonProperties:
  endpointUrl: https://preview.liquidpresentation.com
  accessKey: AKIA3O5FP4PBUVNTHW6P
  secretKey: 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
  bucketName: lpgen2.repo
  region: us-east-2
  
spring:
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enable-spring-el-compiler: true
    cache: true
    template-resolver-order: 1

profitCalculator:
  protectPassword: Protected123.
  

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.liquidpresentaion: DEBUG
  file: /home/ubuntu/cocktail.log

#spring:
#  jackson:
#    time-zone: Asia/Shanghai