#!/bin/bash

echo "beginning shutdown ..."
ps -ef | grep -i '\-jar' | grep -v grep | cut -c 9-15 | xargs kill -s 9
echo "end shutdown"
#isExistApp = `pgrep httpd`
#if [[ -n  $isExistApp ]]; then
#    service httpd stop        
#fi

